LehrFEM++: ecu_scheme::experiments::RotatingHumpSolution< SCALAR > Class Template Reference
ecu_scheme::experiments::RotatingHumpSolution< SCALAR > Class Template Reference
Class for generating the Rotating Hump experiment setup and computing the solution.
#include </home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/experiments/advection_one_form_experiments/rotating_hump/rotating_hump_sol.h>
Public Member Functions
RotatingHumpSolution ()=default
~RotatingHumpSolution ()=default
RotatingHumpSolution (const RotatingHumpSolution &other)=default
RotatingHumpSolution (RotatingHumpSolution &&other) noexcept=default
RotatingHumpSolution & operator= (const RotatingHumpSolution &other)=default
RotatingHumpSolution & operator= (RotatingHumpSolution &&other) noexcept=default
RotatingHumpSolution (const std::shared_ptr< lf::uscalfe::UniformScalarFESpace< SCALAR >> &fe_space)
Eigen::Vector< double, Eigen::Dynamic > ComputeSolution (std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> boundary_condition, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> forcing_term) const
Computes the solution of the Rotating Hump experiment.
Private Attributes
std::shared_ptr< lf::uscalfe::UniformScalarFESpace< SCALAR > > fe_space_
Detailed Description
template<typename SCALAR>
class ecu_scheme::experiments::RotatingHumpSolution< SCALAR >
Class for generating the Rotating Hump experiment setup and computing the solution.
Template Parameters
SCALAR the scalar type of an underlying Lagrangian finite element space
Definition at line 55 of file rotating_hump_sol.h.
Constructor & Destructor Documentation
RotatingHumpSolution() [1/4]
template<typename SCALAR > ecu_scheme::experiments::RotatingHumpSolution< SCALAR >::RotatingHumpSolution () default
~RotatingHumpSolution()
template<typename SCALAR > ecu_scheme::experiments::RotatingHumpSolution< SCALAR >::~RotatingHumpSolution () default
RotatingHumpSolution() [2/4]
template<typename SCALAR > ecu_scheme::experiments::RotatingHumpSolution< SCALAR >::RotatingHumpSolution (const RotatingHumpSolution< SCALAR > & other) default
RotatingHumpSolution() [3/4]
template<typename SCALAR > ecu_scheme::experiments::RotatingHumpSolution< SCALAR >::RotatingHumpSolution (RotatingHumpSolution< SCALAR > && other) default noexcept
RotatingHumpSolution() [4/4]
template<typename SCALAR > ecu_scheme::experiments::RotatingHumpSolution< SCALAR >::RotatingHumpSolution (const std::shared_ptr< lf::uscalfe::UniformScalarFESpace< SCALAR >> & fe_space) inline explicit
Definition at line 65 of file rotating_hump_sol.h.
Member Function Documentation
ComputeSolution()
template<typename SCALAR > Eigen::Vector<double, Eigen::Dynamic> ecu_scheme::experiments::RotatingHumpSolution< SCALAR >::ComputeSolution (std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> boundary_condition, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> forcing_term) const inline
Computes the solution of the Rotating Hump experiment.
Parameters
velocity vector valued velocity field
boundary_condition vector valued Dirichlet boundary condition
forcing_term vector valued source term
Returns
solution vector
Definition at line 77 of file rotating_hump_sol.h.
References lf::assemble::AssembleMatrixLocally(), ecu_scheme::experiments::EnforceInflowBDCOneform(), ecu_scheme::experiments::RotatingHumpSolution< SCALAR >::fe_space_, lf::base::RefEl::kSegment(), lf::base::RefEl::kTria(), lf::assemble::COOMatrix< SCALAR >::makeSparse(), and lf::assemble::DofHandler::NumDofs().
operator=() [1/2]
template<typename SCALAR > RotatingHumpSolution& ecu_scheme::experiments::RotatingHumpSolution< SCALAR >::operator= (const RotatingHumpSolution< SCALAR > & other) default
operator=() [2/2]
template<typename SCALAR > RotatingHumpSolution& ecu_scheme::experiments::RotatingHumpSolution< SCALAR >::operator= (RotatingHumpSolution< SCALAR > && other) default noexcept
Member Data Documentation
fe_space_
template<typename SCALAR > std::shared_ptr<lf::uscalfe::UniformScalarFESpace<SCALAR> > ecu_scheme::experiments::RotatingHumpSolution< SCALAR >::fe_space_ private
Definition at line 161 of file rotating_hump_sol.h.
Referenced by ecu_scheme::experiments::RotatingHumpSolution< SCALAR >::ComputeSolution().
The documentation for this class was generated from the following file:
/home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/experiments/advection_one_form_experiments/rotating_hump/rotating_hump_sol.h