LehrFEM++: ecu_scheme::assemble::ConvectionUpwindMatrixProvider< SCALAR, FUNCTOR > Class Template Reference
ecu_scheme::assemble::ConvectionUpwindMatrixProvider< SCALAR, FUNCTOR > Class Template Reference
#include </home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/assemble/convection_upwind_matrix_provider.h>
Public Member Functions
ConvectionUpwindMatrixProvider (const std::shared_ptr< lf::fe::ScalarFESpace< SCALAR >> &fe_space, FUNCTOR v, lf::mesh::utils::CodimMeshDataSet< double > masses)
Constructor for the ConvectionUpwindMatrixProvider class for the linear finite element space.
ConvectionUpwindMatrixProvider (const std::shared_ptr< lf::fe::ScalarFESpace< SCALAR >> &fe_space, FUNCTOR v, lf::mesh::utils::CodimMeshDataSet< double > masses_vertices, lf::mesh::utils::CodimMeshDataSet< double > masses_edges)
Constructor for the ConvectionUpwindMatrixProvider class for the quadratic finite element space.
Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > Eval (const lf::mesh::Entity &entity)
main routine for the computation of element matrices of variable size depending on the finite element space
bool isActive (const lf::mesh::Entity &) const
Default implementation: all cells are active.
Private Attributes
FUNCTOR v_
std::shared_ptr< lf::fe::ScalarFESpace< SCALAR > > fe_space_
lf::mesh::utils::CodimMeshDataSet< double > masses_vertices_
lf::mesh::utils::CodimMeshDataSet< double > masses_edges_
Detailed Description
template<typename SCALAR, typename FUNCTOR>
class ecu_scheme::assemble::ConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >
Definition at line 58 of file convection_upwind_matrix_provider.h.
Constructor & Destructor Documentation
ConvectionUpwindMatrixProvider() [1/2]
template<typename SCALAR , typename FUNCTOR > ecu_scheme::assemble::ConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::ConvectionUpwindMatrixProvider (const std::shared_ptr< lf::fe::ScalarFESpace< SCALAR >> & fe_space, FUNCTOR v, lf::mesh::utils::CodimMeshDataSet< double > masses)
Constructor for the ConvectionUpwindMatrixProvider class for the linear finite element space.
Parameters
fe_space reference to the finite element space
v functor for the velocity field
Definition at line 109 of file convection_upwind_matrix_provider.h.
ConvectionUpwindMatrixProvider() [2/2]
template<typename SCALAR , typename FUNCTOR > ecu_scheme::assemble::ConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::ConvectionUpwindMatrixProvider (const std::shared_ptr< lf::fe::ScalarFESpace< SCALAR >> & fe_space, FUNCTOR v, lf::mesh::utils::CodimMeshDataSet< double > masses_vertices, lf::mesh::utils::CodimMeshDataSet< double > masses_edges)
Constructor for the ConvectionUpwindMatrixProvider class for the quadratic finite element space.
Parameters
fe_space
v
masses_vertices
masses_edges
Definition at line 115 of file convection_upwind_matrix_provider.h.
Member Function Documentation
Eval()
template<typename SCALAR , typename FUNCTOR > Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > ecu_scheme::assemble::ConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::Eval (const lf::mesh::Entity & entity)
main routine for the computation of element matrices of variable size depending on the finite element space
Parameters
entity reference to the TRIANGULAR cell for which the element matrix is to be computed
Returns
an nxn matrix where n is the number of shape functions of the cell
Definition at line 126 of file convection_upwind_matrix_provider.h.
References ecu_scheme::assemble::computeOutwardNormalsTria(), lf::geometry::Corners(), lf::mesh::Entity::Geometry(), lf::base::RefEl::kTria(), lf::mesh::Entity::RefEl(), lf::mesh::Entity::SubEntities(), and lf::geometry::Volume().
isActive()
template<typename SCALAR , typename FUNCTOR > bool ecu_scheme::assemble::ConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::isActive (const lf::mesh::Entity &) const inline
Default implementation: all cells are active.
Definition at line 94 of file convection_upwind_matrix_provider.h.
Member Data Documentation
fe_space_
template<typename SCALAR , typename FUNCTOR > std::shared_ptr<lf::fe::ScalarFESpace<SCALAR> > ecu_scheme::assemble::ConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::fe_space_ private
Definition at line 101 of file convection_upwind_matrix_provider.h.
masses_edges_
template<typename SCALAR , typename FUNCTOR > lf::mesh::utils::CodimMeshDataSet<double> ecu_scheme::assemble::ConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::masses_edges_ private
Definition at line 105 of file convection_upwind_matrix_provider.h.
masses_vertices_
template<typename SCALAR , typename FUNCTOR > lf::mesh::utils::CodimMeshDataSet<double> ecu_scheme::assemble::ConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::masses_vertices_ private
Definition at line 103 of file convection_upwind_matrix_provider.h.
v_
template<typename SCALAR , typename FUNCTOR > FUNCTOR ecu_scheme::assemble::ConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::v_ private
Definition at line 99 of file convection_upwind_matrix_provider.h.
The documentation for this class was generated from the following file:
/home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/assemble/convection_upwind_matrix_provider.h