LehrFEM++: ecu_scheme::mesh::BasicMeshBuilder Class Reference
ecu_scheme::mesh::BasicMeshBuilder Class Reference
Builds a triangular tensor product mesh on the unit square.
#include </home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/mesh/basic_mesh_builder.h>
Public Member Functions
BasicMeshBuilder ()
Default constructor that makes a hybrid2d mesh factory Check implementation of BasicMeshBuilder::Build() for default values.
~BasicMeshBuilder ()=default
BasicMeshBuilder (std::unique_ptr< lf::mesh::MeshFactory > mesh_factory)
void SetNumCellsX (unsigned int num_cells_x)
Sets the number of cells in direction x.
void SetNumCellsY (unsigned int num_cells_y)
Sets the number of cells in direction y.
std::shared_ptr< lf::mesh::Mesh > Build ()
Builds a mesh from the mesh factory.
std::shared_ptr< lf::mesh::Mesh > Build (double topLeftCornerX, double topLeftCornerY, double topRightCornerX, double topRightCornerY)
Builds a tensor product mesh with an arbitrary dimension of the square.
Private Attributes
uint num_cells_x_ {}
uint num_cells_y_ {}
std::unique_ptr< lf::mesh::MeshFactory > mesh_factory_
Detailed Description
Builds a triangular tensor product mesh on the unit square.
Some experiments discussed in the thesis require a simple tensor product mesh on the unit square This class builds such a mesh with variable number of cells in each direction
Definition at line 21 of file basic_mesh_builder.h.
Constructor & Destructor Documentation
BasicMeshBuilder() [1/2]
ecu_scheme::mesh::BasicMeshBuilder::BasicMeshBuilder ()
Default constructor that makes a hybrid2d mesh factory Check implementation of BasicMeshBuilder::Build() for default values.
Default constructor that makes a hybrid2d mesh factory.
Definition at line 12 of file basic_mesh_builder.cc.
References mesh_factory_, SetNumCellsX(), and SetNumCellsY().
~BasicMeshBuilder()
ecu_scheme::mesh::BasicMeshBuilder::~BasicMeshBuilder () default
BasicMeshBuilder() [2/2]
ecu_scheme::mesh::BasicMeshBuilder::BasicMeshBuilder (std::unique_ptr< lf::mesh::MeshFactory > mesh_factory) inline explicit
Definition at line 29 of file basic_mesh_builder.h.
Member Function Documentation
Build() [1/2]
std::shared_ptr< lf::mesh::Mesh > ecu_scheme::mesh::BasicMeshBuilder::Build ()
Builds a mesh from the mesh factory.
Returns
a shared pointer to the mesh
Definition at line 18 of file basic_mesh_builder.cc.
References lf::mesh::utils::TPTriagMeshBuilder::Build(), mesh_factory_, num_cells_x_, num_cells_y_, lf::mesh::utils::StructuredMeshBuilder::setBottomLeftCorner(), and lf::mesh::utils::StructuredMeshBuilder::setNumYCells().
Build() [2/2]
std::shared_ptr< lf::mesh::Mesh > ecu_scheme::mesh::BasicMeshBuilder::Build (double topLeftCornerX, double topLeftCornerY, double topRightCornerX, double topRightCornerY)
Builds a tensor product mesh with an arbitrary dimension of the square.
Parameters
topLeftCornerX x coordinate of the top left corner of the square
topLeftCornerY y coordinate of the top left corner of the square
topRightCornerX x coordinate of the top right corner of the square
topRightCornerY y coordinate of the top right corner of the square
Returns
a shared pointer to the mesh
Definition at line 37 of file basic_mesh_builder.cc.
References lf::mesh::utils::TPTriagMeshBuilder::Build(), mesh_factory_, num_cells_x_, num_cells_y_, lf::mesh::utils::StructuredMeshBuilder::setBottomLeftCorner(), and lf::mesh::utils::StructuredMeshBuilder::setNumYCells().
SetNumCellsX()
void ecu_scheme::mesh::BasicMeshBuilder::SetNumCellsX (unsigned int num_cells_x) inline
Sets the number of cells in direction x.
Parameters
num_cells_x Number of cells in direction x
Definition at line 38 of file basic_mesh_builder.h.
References num_cells_x_.
Referenced by BasicMeshBuilder().
SetNumCellsY()
void ecu_scheme::mesh::BasicMeshBuilder::SetNumCellsY (unsigned int num_cells_y) inline
Sets the number of cells in direction y.
Parameters
num_cells_y number of cells in direction y
Definition at line 43 of file basic_mesh_builder.h.
References num_cells_y_.
Referenced by BasicMeshBuilder().
Member Data Documentation
mesh_factory_
std::unique_ptr<lf::mesh::MeshFactory> ecu_scheme::mesh::BasicMeshBuilder::mesh_factory_ private
Definition at line 66 of file basic_mesh_builder.h.
Referenced by BasicMeshBuilder(), and Build().
num_cells_x_
uint ecu_scheme::mesh::BasicMeshBuilder::num_cells_x_ {} private
Definition at line 64 of file basic_mesh_builder.h.
Referenced by Build(), and SetNumCellsX().
num_cells_y_
uint ecu_scheme::mesh::BasicMeshBuilder::num_cells_y_ {} private
Definition at line 65 of file basic_mesh_builder.h.
Referenced by Build(), and SetNumCellsY().
The documentation for this class was generated from the following files:
/home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/mesh/basic_mesh_builder.h
/home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/mesh/basic_mesh_builder.cc