LehrFEM++: ecu_scheme::assemble::FifteenPointUpwindMatrixProvider< SCALAR, FUNCTOR > Class Template Reference
ecu_scheme::assemble::FifteenPointUpwindMatrixProvider< SCALAR, FUNCTOR > Class Template Reference
Class providing the element matrix for the 15-point upwind scheme The element matrix provider evaluates the convective bilinear form for the 15-point upwind scheme \(b_h^{full}(u_h,v_h) \) presented in section 2.1.1 of the thesis.
#include </home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/assemble/fifteen_point_upwind_matrix_provider.h>
Public Member Functions
FifteenPointUpwindMatrixProvider (const std::shared_ptr< lf::fe::ScalarFESpace< SCALAR >> &fe_space, FUNCTOR v, lf::mesh::utils::CodimMeshDataSet< double > masses_vertices, lf::mesh::utils::CodimMeshDataSet< double > masses_edge_midpoints, lf::mesh::utils::CodimMeshDataSet< double > masses_edges, lf::mesh::utils::CodimMeshDataSet< double > masses_cells)
Constructor for the Element Matrix Provider for the 15-point upwind scheme.
Eigen::Matrix< SCALAR, 6, 6 > Eval (const lf::mesh::Entity &entity)
Evaluates the element matrix for a given entity.
bool isActive (const lf::mesh::Entity &) const
Default implementation: all cells are active.
Private Attributes
FUNCTOR v_
std::shared_ptr< lf::fe::ScalarFESpace< SCALAR > > fe_space_
lf::mesh::utils::CodimMeshDataSet< double > masses_vertices_
lf::mesh::utils::CodimMeshDataSet< double > masses_edge_midpoints_
lf::mesh::utils::CodimMeshDataSet< double > masses_edges_
lf::mesh::utils::CodimMeshDataSet< double > masses_cells_
Detailed Description
template<typename SCALAR, typename FUNCTOR>
class ecu_scheme::assemble::FifteenPointUpwindMatrixProvider< SCALAR, FUNCTOR >
Class providing the element matrix for the 15-point upwind scheme The element matrix provider evaluates the convective bilinear form for the 15-point upwind scheme \(b_h^{full}(u_h,v_h) \) presented in section 2.1.1 of the thesis.
Template Parameters
SCALAR scalar type of the FE space
FUNCTOR velocity field functor type
Definition at line 76 of file fifteen_point_upwind_matrix_provider.h.
Constructor & Destructor Documentation
FifteenPointUpwindMatrixProvider()
template<typename SCALAR , typename FUNCTOR > ecu_scheme::assemble::FifteenPointUpwindMatrixProvider< SCALAR, FUNCTOR >::FifteenPointUpwindMatrixProvider (const std::shared_ptr< lf::fe::ScalarFESpace< SCALAR >> & fe_space, FUNCTOR v, lf::mesh::utils::CodimMeshDataSet< double > masses_vertices, lf::mesh::utils::CodimMeshDataSet< double > masses_edge_midpoints, lf::mesh::utils::CodimMeshDataSet< double > masses_edges, lf::mesh::utils::CodimMeshDataSet< double > masses_cells)
Constructor for the Element Matrix Provider for the 15-point upwind scheme.
Parameters
fe_space reference to the FE space
v velocity field
masses_vertices Data structure containing the masses m(p) for all vertices of the mesh
masses_edge_midpoints Data structure containing the masses m(p) for all midpoints of edges of the mesh
masses_edges Data structure containing the masses m(p) for all quadrature points lying on edges of the mesh
masses_cells Data structure containing the masses m(p) for all quadrature points lying inside triangle cells of the mesh
Definition at line 119 of file fifteen_point_upwind_matrix_provider.h.
Member Function Documentation
Eval()
template<typename SCALAR , typename FUNCTOR > Eigen::Matrix< SCALAR, 6, 6 > ecu_scheme::assemble::FifteenPointUpwindMatrixProvider< SCALAR, FUNCTOR >::Eval (const lf::mesh::Entity & entity)
Evaluates the element matrix for a given entity.
Parameters
entity underlying entity
Returns
Element matrix for the 15-point upwind scheme
Definition at line 135 of file fifteen_point_upwind_matrix_provider.h.
References ecu_scheme::assemble::computeOutwardNormalsTria(), lf::geometry::Corners(), lf::mesh::Entity::Geometry(), lf::geometry::Geometry::Global(), ecu_scheme::assemble::prepareFifteenPointQuadRule(), lf::mesh::Entity::SubEntities(), and lf::geometry::Volume().
isActive()
template<typename SCALAR , typename FUNCTOR > bool ecu_scheme::assemble::FifteenPointUpwindMatrixProvider< SCALAR, FUNCTOR >::isActive (const lf::mesh::Entity &) const inline
Default implementation: all cells are active.
Definition at line 107 of file fifteen_point_upwind_matrix_provider.h.
Member Data Documentation
fe_space_
template<typename SCALAR , typename FUNCTOR > std::shared_ptr<lf::fe::ScalarFESpace<SCALAR> > ecu_scheme::assemble::FifteenPointUpwindMatrixProvider< SCALAR, FUNCTOR >::fe_space_ private
Definition at line 111 of file fifteen_point_upwind_matrix_provider.h.
masses_cells_
template<typename SCALAR , typename FUNCTOR > lf::mesh::utils::CodimMeshDataSet<double> ecu_scheme::assemble::FifteenPointUpwindMatrixProvider< SCALAR, FUNCTOR >::masses_cells_ private
Definition at line 115 of file fifteen_point_upwind_matrix_provider.h.
masses_edge_midpoints_
template<typename SCALAR , typename FUNCTOR > lf::mesh::utils::CodimMeshDataSet<double> ecu_scheme::assemble::FifteenPointUpwindMatrixProvider< SCALAR, FUNCTOR >::masses_edge_midpoints_ private
Definition at line 113 of file fifteen_point_upwind_matrix_provider.h.
masses_edges_
template<typename SCALAR , typename FUNCTOR > lf::mesh::utils::CodimMeshDataSet<double> ecu_scheme::assemble::FifteenPointUpwindMatrixProvider< SCALAR, FUNCTOR >::masses_edges_ private
Definition at line 114 of file fifteen_point_upwind_matrix_provider.h.
masses_vertices_
template<typename SCALAR , typename FUNCTOR > lf::mesh::utils::CodimMeshDataSet<double> ecu_scheme::assemble::FifteenPointUpwindMatrixProvider< SCALAR, FUNCTOR >::masses_vertices_ private
Definition at line 112 of file fifteen_point_upwind_matrix_provider.h.
v_
template<typename SCALAR , typename FUNCTOR > FUNCTOR ecu_scheme::assemble::FifteenPointUpwindMatrixProvider< SCALAR, FUNCTOR >::v_ private
Definition at line 110 of file fifteen_point_upwind_matrix_provider.h.
The documentation for this class was generated from the following file:
/home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/assemble/fifteen_point_upwind_matrix_provider.h