LehrFEM++: ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V > Class Template Reference
ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V > Class Template Reference
Assemble the SUPG element matrix for the convection-diffusion boundary value problem where the implementation is based on a combination of techniques from the NumPDE Lecture.
#include </home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/assemble/supg_matrix_provider.h>
Public Member Functions
SUPGElementMatrixProvider (const SUPGElementMatrixProvider &)=delete
SUPGElementMatrixProvider (SUPGElementMatrixProvider &&) noexcept=default
SUPGElementMatrixProvider & operator= (const SUPGElementMatrixProvider &)=delete
SUPGElementMatrixProvider & operator= (SUPGElementMatrixProvider &&)=delete
SUPGElementMatrixProvider (MESHFUNCTION_V &velocity, bool use_delta=true)
virtual bool isActive (const lf::mesh::Entity &)
Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic > Eval (const lf::mesh::Entity &cell)
virtual ~SUPGElementMatrixProvider ()=default
Private Attributes
const lf::quad::QuadRule qr_ {lf::quad::make_TriaQR_P6O4()}
MESHFUNCTION_V & velocity_
Eigen::MatrixXd val_ref_lsf_
Eigen::MatrixXd grad_ref_lsf_
bool use_delta_
Detailed Description
template<class MESHFUNCTION_V>
class ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >
Assemble the SUPG element matrix for the convection-diffusion boundary value problem where the implementation is based on a combination of techniques from the NumPDE Lecture.
Template Parameters
MESHFUNCTION_V type of mesh function providing the velocity field
Definition at line 34 of file supg_matrix_provider.h.
Constructor & Destructor Documentation
SUPGElementMatrixProvider() [1/3]
template<class MESHFUNCTION_V > ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::SUPGElementMatrixProvider (const SUPGElementMatrixProvider< MESHFUNCTION_V > &) delete
SUPGElementMatrixProvider() [2/3]
template<class MESHFUNCTION_V > ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::SUPGElementMatrixProvider (SUPGElementMatrixProvider< MESHFUNCTION_V > &&) default noexcept
SUPGElementMatrixProvider() [3/3]
template<class MESHFUNCTION_V > ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::SUPGElementMatrixProvider (MESHFUNCTION_V & velocity, bool use_delta = true) explicit
Definition at line 65 of file supg_matrix_provider.h.
References lf::uscalfe::FeLagrangeO2Tria< SCALAR >::EvalReferenceShapeFunctions(), ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::grad_ref_lsf_, lf::uscalfe::FeLagrangeO2Tria< SCALAR >::GradientsReferenceShapeFunctions(), lf::base::RefEl::kTria(), lf::quad::QuadRule::NumPoints(), lf::uscalfe::FeLagrangeO2Tria< SCALAR >::NumRefShapeFunctions(), lf::quad::QuadRule::Points(), ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::qr_, lf::quad::QuadRule::RefEl(), lf::uscalfe::FeLagrangeO2Tria< SCALAR >::RefEl(), and ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::val_ref_lsf_.
~SUPGElementMatrixProvider()
template<class MESHFUNCTION_V > virtual ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::~SUPGElementMatrixProvider () virtual default
Member Function Documentation
Eval()
template<class MESHFUNCTION_V > Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic > ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::Eval (const lf::mesh::Entity & cell)
Definition at line 84 of file supg_matrix_provider.h.
References lf::geometry::Corners(), lf::geometry::Geometry::DimGlobal(), lf::mesh::Entity::Geometry(), lf::geometry::Geometry::IntegrationElement(), lf::geometry::Geometry::JacobianInverseGramian(), lf::base::RefEl::kTria(), and lf::mesh::Entity::RefEl().
isActive()
template<class MESHFUNCTION_V > virtual bool ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::isActive (const lf::mesh::Entity &) inline virtual
Definition at line 45 of file supg_matrix_provider.h.
operator=() [1/2]
template<class MESHFUNCTION_V > SUPGElementMatrixProvider& ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::operator= (const SUPGElementMatrixProvider< MESHFUNCTION_V > &) delete
operator=() [2/2]
template<class MESHFUNCTION_V > SUPGElementMatrixProvider& ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::operator= (SUPGElementMatrixProvider< MESHFUNCTION_V > &&) delete
Member Data Documentation
grad_ref_lsf_
template<class MESHFUNCTION_V > Eigen::MatrixXd ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::grad_ref_lsf_ private
Definition at line 59 of file supg_matrix_provider.h.
Referenced by ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::SUPGElementMatrixProvider().
qr_
template<class MESHFUNCTION_V > const lf::quad::QuadRule ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::qr_ {lf::quad::make_TriaQR_P6O4()} private
Definition at line 53 of file supg_matrix_provider.h.
Referenced by ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::SUPGElementMatrixProvider().
use_delta_
template<class MESHFUNCTION_V > bool ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::use_delta_ private
Definition at line 61 of file supg_matrix_provider.h.
val_ref_lsf_
template<class MESHFUNCTION_V > Eigen::MatrixXd ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::val_ref_lsf_ private
Definition at line 57 of file supg_matrix_provider.h.
Referenced by ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::SUPGElementMatrixProvider().
velocity_
template<class MESHFUNCTION_V > MESHFUNCTION_V& ecu_scheme::assemble::SUPGElementMatrixProvider< MESHFUNCTION_V >::velocity_ private
Definition at line 55 of file supg_matrix_provider.h.
The documentation for this class was generated from the following file:
/home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/assemble/supg_matrix_provider.h