LehrFEM++: ecu_scheme::experiments::ConstVeloSolution< SCALAR > Class Template Reference
ecu_scheme::experiments::ConstVeloSolution< SCALAR > Class Template Reference
#include </home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/experiments/const_velo/const_velo_solution.h>
Public Member Functions
ConstVeloSolution ()=default
~ConstVeloSolution ()=default
ConstVeloSolution (const ConstVeloSolution &other)=default
ConstVeloSolution (ConstVeloSolution &&other) noexcept=default
ConstVeloSolution & operator= (const ConstVeloSolution &other)=default
ConstVeloSolution & operator= (ConstVeloSolution &&other) noexcept=default
ConstVeloSolution (const std::shared_ptr< lf::uscalfe::UniformScalarFESpace< SCALAR >> &fe_space)
Eigen::VectorXd ComputeSolution (std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> test_function, std::string method_name) const
Private Attributes
std::shared_ptr< lf::uscalfe::UniformScalarFESpace< SCALAR > > fe_space_
Detailed Description
template<typename SCALAR>
class ecu_scheme::experiments::ConstVeloSolution< SCALAR >
Definition at line 38 of file const_velo_solution.h.
Constructor & Destructor Documentation
ConstVeloSolution() [1/4]
template<typename SCALAR > ecu_scheme::experiments::ConstVeloSolution< SCALAR >::ConstVeloSolution () default
~ConstVeloSolution()
template<typename SCALAR > ecu_scheme::experiments::ConstVeloSolution< SCALAR >::~ConstVeloSolution () default
ConstVeloSolution() [2/4]
template<typename SCALAR > ecu_scheme::experiments::ConstVeloSolution< SCALAR >::ConstVeloSolution (const ConstVeloSolution< SCALAR > & other) default
ConstVeloSolution() [3/4]
template<typename SCALAR > ecu_scheme::experiments::ConstVeloSolution< SCALAR >::ConstVeloSolution (ConstVeloSolution< SCALAR > && other) default noexcept
ConstVeloSolution() [4/4]
template<typename SCALAR > ecu_scheme::experiments::ConstVeloSolution< SCALAR >::ConstVeloSolution (const std::shared_ptr< lf::uscalfe::UniformScalarFESpace< SCALAR >> & fe_space) inline explicit
Definition at line 47 of file const_velo_solution.h.
Member Function Documentation
ComputeSolution()
template<typename SCALAR > Eigen::VectorXd ecu_scheme::experiments::ConstVeloSolution< SCALAR >::ComputeSolution (std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> test_function, std::string method_name) const inline
Definition at line 52 of file const_velo_solution.h.
References lf::assemble::AssembleMatrixLocally(), lf::assemble::AssembleVectorLocally(), ecu_scheme::experiments::EnforceBoundaryConditions(), ecu_scheme::experiments::ConstVeloSolution< SCALAR >::fe_space_, ecu_scheme::assemble::initializeMassesQuadratic(), ecu_scheme::assemble::initializeMassesQuadraticEdges(), ecu_scheme::assemble::initMassesCells(), ecu_scheme::assemble::initMassesEdges(), ecu_scheme::assemble::initMassesVert(), and lf::assemble::COOMatrix< SCALAR >::makeSparse().
operator=() [1/2]
template<typename SCALAR > ConstVeloSolution& ecu_scheme::experiments::ConstVeloSolution< SCALAR >::operator= (const ConstVeloSolution< SCALAR > & other) default
operator=() [2/2]
template<typename SCALAR > ConstVeloSolution& ecu_scheme::experiments::ConstVeloSolution< SCALAR >::operator= (ConstVeloSolution< SCALAR > && other) default noexcept
Member Data Documentation
fe_space_
template<typename SCALAR > std::shared_ptr<lf::uscalfe::UniformScalarFESpace<SCALAR> > ecu_scheme::experiments::ConstVeloSolution< SCALAR >::fe_space_ private
Definition at line 114 of file const_velo_solution.h.
Referenced by ecu_scheme::experiments::ConstVeloSolution< SCALAR >::ComputeSolution().
The documentation for this class was generated from the following file:
/home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/experiments/const_velo/const_velo_solution.h