LehrFEM++: ecu_scheme::experiments::ConcentricStreamSolution< SCALAR > Class Template Reference
ecu_scheme::experiments::ConcentricStreamSolution< SCALAR > Class Template Reference
#include </home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/experiments/concentric_stream/concentric_stream_solution.h>
Public Member Functions
ConcentricStreamSolution ()=delete
~ConcentricStreamSolution ()=default
ConcentricStreamSolution (const std::shared_ptr< lf::uscalfe::UniformScalarFESpace< SCALAR >> &fe_space)
Eigen::Vector< double, Eigen::Dynamic > ComputeSolution (double eps, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet) const
Eigen::Vector< double, Eigen::Dynamic > ComputeSolutionMultipleMethods (double eps, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> test_functor, std::string method_name) const
Compute the solution for the given problem using multiple methods.
Private Attributes
std::shared_ptr< lf::uscalfe::UniformScalarFESpace< SCALAR > > fe_space_
Detailed Description
template<typename SCALAR>
class ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >
Definition at line 51 of file concentric_stream_solution.h.
Constructor & Destructor Documentation
ConcentricStreamSolution() [1/2]
template<typename SCALAR > ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ConcentricStreamSolution () delete
~ConcentricStreamSolution()
template<typename SCALAR > ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::~ConcentricStreamSolution () default
ConcentricStreamSolution() [2/2]
template<typename SCALAR > ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ConcentricStreamSolution (const std::shared_ptr< lf::uscalfe::UniformScalarFESpace< SCALAR >> & fe_space) inline explicit
Definition at line 56 of file concentric_stream_solution.h.
Member Function Documentation
ComputeSolution()
template<typename SCALAR > Eigen::Vector<double, Eigen::Dynamic> ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolution (double eps, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet) const inline
Definition at line 61 of file concentric_stream_solution.h.
References lf::assemble::AssembleMatrixLocally(), lf::mesh::Entity::Entity(), ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::fe_space_, ecu_scheme::experiments::flagNodesOnInflowBoundary(), ecu_scheme::assemble::initializeMasses(), ecu_scheme::assemble::initializeMassesQuadratic(), ecu_scheme::assemble::initializeMassesQuadraticEdges(), lf::base::RefEl::kPoint(), lf::assemble::COOMatrix< SCALAR >::makeSparse(), and lf::fe::NodalProjection().
ComputeSolutionMultipleMethods()
template<typename SCALAR > Eigen::Vector<double, Eigen::Dynamic> ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolutionMultipleMethods (double eps, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> test_functor, std::string method_name) const inline
Compute the solution for the given problem using multiple methods.
Parameters
eps
velocity
dirichlet
method_name should be either {"UPWIND", "STABLE_UPWIND", "15P_UPWIND"}
Returns
Definition at line 164 of file concentric_stream_solution.h.
References lf::assemble::AssembleMatrixLocally(), lf::assemble::AssembleVectorLocally(), ecu_scheme::experiments::EnforceBoundaryConditions(), ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::fe_space_, ecu_scheme::assemble::initializeMasses(), ecu_scheme::assemble::initializeMassesQuadratic(), ecu_scheme::assemble::initializeMassesQuadraticEdges(), ecu_scheme::assemble::initMassesCells(), ecu_scheme::assemble::initMassesCellsFifteenQuadRule(), ecu_scheme::assemble::initMassesEdgeMidpointsFifteenQuadRule(), ecu_scheme::assemble::initMassesEdgeOffFifteenQuadRule(), ecu_scheme::assemble::initMassesEdges(), ecu_scheme::assemble::initMassesVert(), ecu_scheme::assemble::initMassesVerticesFifteenQuadRule(), and lf::assemble::COOMatrix< SCALAR >::makeSparse().
Member Data Documentation
fe_space_
template<typename SCALAR > std::shared_ptr<lf::uscalfe::UniformScalarFESpace<SCALAR> > ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::fe_space_ private
Definition at line 307 of file concentric_stream_solution.h.
Referenced by ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolution(), and ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolutionMultipleMethods().
The documentation for this class was generated from the following file:
/home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/experiments/concentric_stream/concentric_stream_solution.h