LehrFEM++: ecu_scheme::assemble::SupgConvectiveEMP< FUNCTOR > Class Template Reference
ecu_scheme::assemble::SupgConvectiveEMP< FUNCTOR > Class Template Reference
Computes the local matrices for the convective term based on linear FE and trapezoidal rule.
#include </home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/assemble/supg_linear_matrix_provider.h>
Public Member Functions
SupgConvectiveEMP (FUNCTOR v)
Eigen::Matrix3d Eval (const lf::mesh::Entity &entity)
main routine for the computation of element matrices
bool isActive (const lf::mesh::Entity &cell) const
Private Attributes
FUNCTOR v_
Detailed Description
template<typename FUNCTOR>
class ecu_scheme::assemble::SupgConvectiveEMP< FUNCTOR >
Computes the local matrices for the convective term based on linear FE and trapezoidal rule.
Template Parameters
FUNCTOR function that defines the vector valued velocity coefficient v.
Definition at line 40 of file supg_linear_matrix_provider.h.
Constructor & Destructor Documentation
SupgConvectiveEMP()
template<typename FUNCTOR > ecu_scheme::assemble::SupgConvectiveEMP< FUNCTOR >::SupgConvectiveEMP (FUNCTOR v) inline explicit
Definition at line 42 of file supg_linear_matrix_provider.h.
Member Function Documentation
Eval()
template<typename FUNCTOR > Eigen::Matrix3d ecu_scheme::assemble::SupgConvectiveEMP< FUNCTOR >::Eval (const lf::mesh::Entity & entity)
main routine for the computation of element matrices
Parameters
enttity reference to the TRIANGULAR cell for which the element matrix should be computed.
Returns
a 3x3 matrix containing the element matrix.
Definition at line 59 of file supg_linear_matrix_provider.h.
References lf::geometry::Corners(), lf::mesh::Entity::Geometry(), lf::base::RefEl::kTria(), lf::mesh::Entity::RefEl(), and lf::geometry::Volume().
isActive()
template<typename FUNCTOR > bool ecu_scheme::assemble::SupgConvectiveEMP< FUNCTOR >::isActive (const lf::mesh::Entity & cell) const inline
Definition at line 52 of file supg_linear_matrix_provider.h.
Member Data Documentation
v_
template<typename FUNCTOR > FUNCTOR ecu_scheme::assemble::SupgConvectiveEMP< FUNCTOR >::v_ private
Definition at line 55 of file supg_linear_matrix_provider.h.
The documentation for this class was generated from the following file:
/home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/assemble/supg_linear_matrix_provider.h