LehrFEM++: ecu_scheme::assemble::MeshFunctionOneForm< SCALAR > Class Template Reference
ecu_scheme::assemble::MeshFunctionOneForm< SCALAR > Class Template Reference
#include </home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/assemble/mesh_function_one_form.h>
Public Member Functions
MeshFunctionOneForm (const Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > &mu, const std::shared_ptr< const lf::mesh::Mesh > &mesh_p)
std::vector< Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > > operator() (const lf::mesh::Entity &entity, const Eigen::MatrixXd &local_coords) const
Private Attributes
Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > mu_
std::shared_ptr< const lf::mesh::Mesh > mesh_p_
Detailed Description
template<typename SCALAR>
class ecu_scheme::assemble::MeshFunctionOneForm< SCALAR >
Definition at line 10 of file mesh_function_one_form.h.
Constructor & Destructor Documentation
MeshFunctionOneForm()
template<typename SCALAR > ecu_scheme::assemble::MeshFunctionOneForm< SCALAR >::MeshFunctionOneForm (const Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > & mu, const std::shared_ptr< const lf::mesh::Mesh > & mesh_p) inline
Definition at line 12 of file mesh_function_one_form.h.
Member Function Documentation
operator()()
template<typename SCALAR > std::vector< Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > > ecu_scheme::assemble::MeshFunctionOneForm< SCALAR >::operator() (const lf::mesh::Entity & entity, const Eigen::MatrixXd & local_coords) const
Definition at line 27 of file mesh_function_one_form.h.
References lf::geometry::Corners(), lf::uscalfe::FeLagrangeO1Tria< SCALAR >::EvalReferenceShapeFunctions(), lf::mesh::Entity::Geometry(), lf::uscalfe::FeLagrangeO1Tria< SCALAR >::GradientsReferenceShapeFunctions(), lf::geometry::Geometry::JacobianInverseGramian(), lf::base::RefEl::kTria(), lf::uscalfe::FeLagrangeO1Tria< SCALAR >::NumRefShapeFunctions(), lf::mesh::Entity::RefEl(), lf::mesh::Entity::RelativeOrientations(), lf::mesh::Entity::SubEntities(), and lf::mesh::to_sign().
Member Data Documentation
mesh_p_
template<typename SCALAR > std::shared_ptr<const lf::mesh::Mesh> ecu_scheme::assemble::MeshFunctionOneForm< SCALAR >::mesh_p_ private
Definition at line 22 of file mesh_function_one_form.h.
mu_
template<typename SCALAR > Eigen::Matrix<SCALAR, Eigen::Dynamic, 1> ecu_scheme::assemble::MeshFunctionOneForm< SCALAR >::mu_ private
Definition at line 21 of file mesh_function_one_form.h.
The documentation for this class was generated from the following file:
/home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/assemble/mesh_function_one_form.h