LehrFEM++: ecu_scheme::assemble::SupgStabilizationEMP< FUNCTOR_EPS, FUNCTOR_V, FUNCTOR_F > Class Template Reference
ecu_scheme::assemble::SupgStabilizationEMP< FUNCTOR_EPS, FUNCTOR_V, FUNCTOR_F > Class Template Reference
Computes the local matrices for the stabilization term in the SUPG method based on linear finite elements and the trapezoidal rule .
#include </home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/assemble/supg_linear_matrix_provider.h>
Public Member Functions
SupgStabilizationEMP (FUNCTOR_EPS eps, FUNCTOR_V v, FUNCTOR_F f)
Constructor for the stabilization term.
Eigen::Matrix3d Eval (const lf::mesh::Entity &entity)
main routine, computes the element matrix on a TRIANGULAR entity
bool isActive (const lf::mesh::Entity &cell) const
Default implementation: all cells are active.
Private Attributes
FUNCTOR_EPS eps_
FUNCTOR_V v_
FUNCTOR_F f_
Detailed Description
template<typename FUNCTOR_EPS, typename FUNCTOR_V, typename FUNCTOR_F>
class ecu_scheme::assemble::SupgStabilizationEMP< FUNCTOR_EPS, FUNCTOR_V, FUNCTOR_F >
Computes the local matrices for the stabilization term in the SUPG method based on linear finite elements and the trapezoidal rule .
Definition at line 88 of file supg_linear_matrix_provider.h.
Constructor & Destructor Documentation
SupgStabilizationEMP()
template<typename FUNCTOR_EPS , typename FUNCTOR_V , typename FUNCTOR_F > ecu_scheme::assemble::SupgStabilizationEMP< FUNCTOR_EPS, FUNCTOR_V, FUNCTOR_F >::SupgStabilizationEMP (FUNCTOR_EPS eps, FUNCTOR_V v, FUNCTOR_F f) inline explicit
Constructor for the stabilization term.
Parameters
eps diffusion coefficient
v velocity field
f source function
Definition at line 96 of file supg_linear_matrix_provider.h.
Member Function Documentation
Eval()
template<typename FUNCTOR_EPS , typename FUNCTOR_V , typename FUNCTOR_F > Eigen::Matrix3d ecu_scheme::assemble::SupgStabilizationEMP< FUNCTOR_EPS, FUNCTOR_V, FUNCTOR_F >::Eval (const lf::mesh::Entity & entity)
main routine, computes the element matrix on a TRIANGULAR entity
Definition at line 114 of file supg_linear_matrix_provider.h.
References lf::geometry::Corners(), ecu_scheme::assemble::Delta(), lf::mesh::Entity::Geometry(), lf::base::RefEl::kTria(), lf::mesh::Entity::RefEl(), and lf::geometry::Volume().
isActive()
template<typename FUNCTOR_EPS , typename FUNCTOR_V , typename FUNCTOR_F > bool ecu_scheme::assemble::SupgStabilizationEMP< FUNCTOR_EPS, FUNCTOR_V, FUNCTOR_F >::isActive (const lf::mesh::Entity & cell) const inline
Default implementation: all cells are active.
Definition at line 105 of file supg_linear_matrix_provider.h.
Member Data Documentation
eps_
template<typename FUNCTOR_EPS , typename FUNCTOR_V , typename FUNCTOR_F > FUNCTOR_EPS ecu_scheme::assemble::SupgStabilizationEMP< FUNCTOR_EPS, FUNCTOR_V, FUNCTOR_F >::eps_ private
Definition at line 108 of file supg_linear_matrix_provider.h.
f_
template<typename FUNCTOR_EPS , typename FUNCTOR_V , typename FUNCTOR_F > FUNCTOR_F ecu_scheme::assemble::SupgStabilizationEMP< FUNCTOR_EPS, FUNCTOR_V, FUNCTOR_F >::f_ private
Definition at line 110 of file supg_linear_matrix_provider.h.
v_
template<typename FUNCTOR_EPS , typename FUNCTOR_V , typename FUNCTOR_F > FUNCTOR_V ecu_scheme::assemble::SupgStabilizationEMP< FUNCTOR_EPS, FUNCTOR_V, FUNCTOR_F >::v_ private
Definition at line 109 of file supg_linear_matrix_provider.h.
The documentation for this class was generated from the following file:
/home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/assemble/supg_linear_matrix_provider.h