LehrFEM++: ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR > Class Template Reference
ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR > Class Template Reference
Class for computing the manufactured solution for the ECU scheme.
#include </home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/experiments/manufactured_sol/manufactured_solution.h>
Public Member Functions
ManufacturedSolutionExperiment ()=delete
~ManufacturedSolutionExperiment ()=default
ManufacturedSolutionExperiment (const ManufacturedSolutionExperiment &other)=default
ManufacturedSolutionExperiment (ManufacturedSolutionExperiment &&other) noexcept=default
ManufacturedSolutionExperiment & operator= (const ManufacturedSolutionExperiment &other)=default
ManufacturedSolutionExperiment & operator= (ManufacturedSolutionExperiment &&other) noexcept=default
ManufacturedSolutionExperiment (const std::shared_ptr< lf::uscalfe::UniformScalarFESpace< SCALAR >> &fe_space)
Eigen::Vector< double, Eigen::Dynamic > ComputeSolution (double eps, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> test, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet) const
Computes the manufactured solution for the ECU scheme.
Eigen::Vector< double, Eigen::Dynamic > ComputeSUPGSolution (double eps, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> test, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet) const
Solves the Convection-Diffusion BVP with nonhomogeneous Dirichlet boundary conditions using the SUPG method and quadratic FE space.
Eigen::Vector< double, Eigen::Dynamic > ComputeStableSolution (double eps, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> test, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet) const
Implemented only for quadratic FE space.
Eigen::Vector< double, Eigen::Dynamic > ComputeFifteenPointQuadRuleSolution (double eps, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> test, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet) const
Private Attributes
std::shared_ptr< lf::uscalfe::UniformScalarFESpace< SCALAR > > fe_space_
Detailed Description
template<typename SCALAR>
class ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >
Class for computing the manufactured solution for the ECU scheme.
Definition at line 29 of file manufactured_solution.h.
Constructor & Destructor Documentation
ManufacturedSolutionExperiment() [1/4]
template<typename SCALAR > ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ManufacturedSolutionExperiment () delete
~ManufacturedSolutionExperiment()
template<typename SCALAR > ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::~ManufacturedSolutionExperiment () default
ManufacturedSolutionExperiment() [2/4]
template<typename SCALAR > ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ManufacturedSolutionExperiment (const ManufacturedSolutionExperiment< SCALAR > & other) default
ManufacturedSolutionExperiment() [3/4]
template<typename SCALAR > ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ManufacturedSolutionExperiment (ManufacturedSolutionExperiment< SCALAR > && other) default noexcept
ManufacturedSolutionExperiment() [4/4]
template<typename SCALAR > ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ManufacturedSolutionExperiment (const std::shared_ptr< lf::uscalfe::UniformScalarFESpace< SCALAR >> & fe_space) inline explicit
Definition at line 46 of file manufactured_solution.h.
Member Function Documentation
ComputeFifteenPointQuadRuleSolution()
template<typename SCALAR > Eigen::Vector<double, Eigen::Dynamic> ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeFifteenPointQuadRuleSolution (double eps, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> test, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet) const inline
Definition at line 302 of file manufactured_solution.h.
References lf::assemble::AssembleMatrixLocally(), lf::assemble::AssembleVectorLocally(), ecu_scheme::experiments::EnforceBoundaryConditions(), ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::fe_space_, ecu_scheme::assemble::initMassesCellsFifteenQuadRule(), ecu_scheme::assemble::initMassesEdgeMidpointsFifteenQuadRule(), ecu_scheme::assemble::initMassesEdgeOffFifteenQuadRule(), ecu_scheme::assemble::initMassesVerticesFifteenQuadRule(), and lf::assemble::COOMatrix< SCALAR >::makeSparse().
ComputeSolution()
template<typename SCALAR > Eigen::Vector<double, Eigen::Dynamic> ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeSolution (double eps, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> test, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet) const inline
Computes the manufactured solution for the ECU scheme.
Parameters
eps Epsilon diffusion coefficient
velocity functor for the velocity field
test test function f
dirichlet dirichlet function g
Returns
Definition at line 59 of file manufactured_solution.h.
References lf::assemble::AssembleMatrixLocally(), lf::assemble::AssembleVectorLocally(), ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::fe_space_, lf::mesh::utils::flagEntitiesOnBoundary(), lf::fe::InitEssentialConditionFromFunction(), ecu_scheme::assemble::initializeMasses(), ecu_scheme::assemble::initializeMassesQuadratic(), ecu_scheme::assemble::initializeMassesQuadraticEdges(), and lf::assemble::COOMatrix< SCALAR >::makeSparse().
ComputeStableSolution()
template<typename SCALAR > Eigen::Vector<double, Eigen::Dynamic> ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeStableSolution (double eps, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> test, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet) const inline
Implemented only for quadratic FE space.
Parameters
eps
velocity
test
dirichlet
Returns
Definition at line 233 of file manufactured_solution.h.
References lf::assemble::AssembleMatrixLocally(), lf::assemble::AssembleVectorLocally(), ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::fe_space_, lf::mesh::utils::flagEntitiesOnBoundary(), lf::fe::InitEssentialConditionFromFunction(), ecu_scheme::assemble::initMassesCells(), ecu_scheme::assemble::initMassesEdges(), ecu_scheme::assemble::initMassesVert(), and lf::assemble::COOMatrix< SCALAR >::makeSparse().
ComputeSUPGSolution()
template<typename SCALAR > Eigen::Vector<double, Eigen::Dynamic> ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeSUPGSolution (double eps, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> test, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet) const inline
Solves the Convection-Diffusion BVP with nonhomogeneous Dirichlet boundary conditions using the SUPG method and quadratic FE space.
Parameters
eps Epsilon diffusion coefficient
velocity functor for the velocity field
test test function f
dirichlet dirichlet boundary condition function g
Returns
Eigen solution vector
Definition at line 155 of file manufactured_solution.h.
References lf::assemble::AssembleMatrixLocally(), lf::assemble::AssembleVectorLocally(), ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::fe_space_, lf::mesh::utils::flagEntitiesOnBoundary(), lf::fe::InitEssentialConditionFromFunction(), and lf::assemble::COOMatrix< SCALAR >::makeSparse().
operator=() [1/2]
template<typename SCALAR > ManufacturedSolutionExperiment& ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::operator= (const ManufacturedSolutionExperiment< SCALAR > & other) default
operator=() [2/2]
template<typename SCALAR > ManufacturedSolutionExperiment& ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::operator= (ManufacturedSolutionExperiment< SCALAR > && other) default noexcept
Member Data Documentation
fe_space_
template<typename SCALAR > std::shared_ptr<lf::uscalfe::UniformScalarFESpace<SCALAR> > ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::fe_space_ private
Definition at line 375 of file manufactured_solution.h.
Referenced by ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeFifteenPointQuadRuleSolution(), ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeSolution(), ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeStableSolution(), and ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeSUPGSolution().
The documentation for this class was generated from the following file:
/home/runner/work/ecu-scheme/ecu-scheme/projects/ecu_scheme/experiments/manufactured_sol/manufactured_solution.h