LehrFEM++: ecu_scheme::experiments Namespace Reference
ecu_scheme::experiments Namespace Reference
Classes
class RotatingHumpSolution
class ConcentricStreamSolution
class ConstVeloSolution
class ManufacturedSolutionExperiment
Class for computing the manufactured solution for the ECU scheme.
Functions
void EnforceBoundaryConditions (const std::shared_ptr< lf::uscalfe::UniformScalarFESpace< double >> &fe_space, lf::assemble::COOMatrix< double > &A, Eigen::VectorXd &phi, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet)
Enforces the Dirichlet boundary conditions at the inflow boundary.
lf::mesh::utils::CodimMeshDataSet< bool > flagNodesOnInflowBoundary (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity)
Flags all nodes on the inflow boundary - basically a different implementation to do the same thing as EnforceBoundaryConditions.
Function Documentation
EnforceBoundaryConditions()
void ecu_scheme::experiments::EnforceBoundaryConditions (const std::shared_ptr< lf::uscalfe::UniformScalarFESpace< double >> & fe_space, lf::assemble::COOMatrix< double > & A, Eigen::VectorXd & phi, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet)
Enforces the Dirichlet boundary conditions at the inflow boundary.
Template Parameters
SCALAR template parameter indicating the scalar type
Parameters
fe_space corresponding finite element space
A Galerkin system matrix
phi Right-hand side vector of the linear system
dirichlet Dirichlet function to be enforced at the inflow boundary
Definition at line 6 of file rotating_hump_sol.cc.
References lf::geometry::Corners(), lf::geometry::Geometry::Geometry(), lf::fe::InitEssentialConditionFromFunction(), lf::base::RefEl::kPoint(), and lf::base::RefEl::kSegment().
Referenced by ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeFifteenPointQuadRuleSolution(), ecu_scheme::experiments::ConstVeloSolution< SCALAR >::ComputeSolution(), ecu_scheme::experiments::RotatingHumpSolution< SCALAR >::ComputeSolution(), and ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolutionMultipleMethods().
flagNodesOnInflowBoundary()
lf::mesh::utils::CodimMeshDataSet< bool > ecu_scheme::experiments::flagNodesOnInflowBoundary (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p, std::function< Eigen::Matrix< double, 2, 1, 0 >(const Eigen::Matrix< double, 2, 1, 0 > &)> velocity)
Flags all nodes on the inflow boundary - basically a different implementation to do the same thing as EnforceBoundaryConditions.
Parameters
mesh_p underlying mesh
velocity velocity field
Returns
Data set of flags for nodes on the inflow boundary
Definition at line 56 of file concentric_stream_solution.cc.
References lf::geometry::Corners(), lf::geometry::Geometry::DimGlobal(), lf::mesh::utils::flagEntitiesOnBoundary(), lf::geometry::Geometry::Geometry(), lf::geometry::Geometry::Global(), and lf::base::RefEl::kTria().
Referenced by ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolution().