LehrFEM++: ecu_scheme::post_processing Namespace Reference
ecu_scheme::post_processing Namespace Reference
Collection of post processing classes and methods.
Classes
struct ExperimentSolutionWrapper
Wrapper for storing the solutions at different refinement levels of an experiment.
Functions
double ComputeMeshWidthTria (std::shared_ptr< const lf::mesh::Mesh > mesh_p)
Computes the mesh width of a triangular mesh which is defined as the maximal edge length.
template<typename MF >
double EvaluateMeshFunction (std::shared_ptr< const lf::mesh::Mesh > mesh_p, MF mf, const Eigen::Vector2d &global, double tol=10E-10)
Evaluates a MeshFunction at a point specified by its global coordinates.
template<typename MF >
std::vector< double > EvaluateMeshFunction (std::shared_ptr< const lf::mesh::Mesh > mesh_p, MF mf, const std::vector< Eigen::Vector2d > &global, double tol=10E-10)
Evaluates a MeshFunction at a set of points specified by their global coordinates.
template<typename CURVE , typename MF >
void SampleMeshFunctionOnCurve (std::shared_ptr< const lf::mesh::Mesh > mesh_p, const CURVE &gamma, const MF &mf, unsigned int num_points, const std::string &file_name, std::pair< double, double > interval={0.0, 1.0})
Sample a mesh function at points along a curve.
template<class MF , typename SQ_F >
std::pair< double, lf::mesh::utils::CodimMeshDataSet< double > > L2norm (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p, const MF &f, const SQ_F &sq_f, const lf::quad::QuadRule &quad_rule)
template<typename MF , typename SQ_F >
std::pair< double, lf::mesh::utils::CodimMeshDataSet< double > > H1seminorm (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p, const MF &f, const SQ_F &sq_f, const lf::quad::QuadRule &quad_rule)
Eigen::Vector2d linearFit (const Eigen::VectorXd &x, const Eigen::VectorXd &y)
double eoc (Eigen::VectorXd &N, Eigen::VectorXd &err, unsigned int from_index=0)
template<typename... Args>
static std::string concat (Args &&... args)
Concatenate objects defining an operator<<(std::ostream&)
template<typename SCALAR , typename MF >
void output_meshfunction_paraview (std::shared_ptr< const lf::fe::ScalarFESpace< SCALAR >> fe_space, MF &mf_analytic, std::string file_name)
template<typename SCALAR >
void output_results (const std::shared_ptr< lf::fe::ScalarFESpace< SCALAR >> &fe_space, Eigen::VectorXd solution_vec, std::string experiment_name)
template<typename SCALAR , typename MF >
void convergence_report_oneform (const ExperimentSolutionWrapper< SCALAR > &solution_collection_wrapper, MF &mf_exact_solution, std::string experiment_name, bool isLinear=false)
template<typename SCALAR , typename MF >
void convergence_comparison_toSUPG (const ExperimentSolutionWrapper< SCALAR > &solution_collection_wrapper_one, const ExperimentSolutionWrapper< SCALAR > &solution_collection_wrapper_two, MF &mf_exact_solution, std::string experiment_name, bool isLinear=false)
template<typename SCALAR , typename MF >
void convergence_comparison_multiple_methods (std::vector< std::pair< ExperimentSolutionWrapper< SCALAR >, std::string >> solution_wrappers_with_name, MF &exact_solution, std::string experiment_name, bool isLinear=false)
Compare the convergence of multiple methods.
Detailed Description
Collection of post processing classes and methods.
Function Documentation
ComputeMeshWidthTria()
double ecu_scheme::post_processing::ComputeMeshWidthTria (std::shared_ptr< const lf::mesh::Mesh > mesh_p)
Computes the mesh width of a triangular mesh which is defined as the maximal edge length.
Parameters
mesh_p underlying triangular mesh
Returns
Mesh width of the mesh
Definition at line 6 of file ecu_tools.cc.
References lf::base::RefEl::kTria(), lf::base::RefEl::RefEl(), lf::mesh::Entity::SubEntities(), and lf::geometry::Volume().
Referenced by convergence_comparison_multiple_methods(), convergence_comparison_toSUPG(), and convergence_report_oneform().
concat()
template<typename... Args> static std::string ecu_scheme::post_processing::concat (Args &&... args) static
Concatenate objects defining an operator<<(std::ostream&)
C++17 specific implementation based on fold expressions Reference: https://stackoverflow.com/a/61002819
Template Parameters
Args variadic template argument pack
Parameters
args variadic pack of objects implementing operator<<(std::ostream&)
Returns
string containing the concatenation of the objects in args
Definition at line 77 of file results_processing.h.
Referenced by convergence_comparison_multiple_methods(), convergence_comparison_toSUPG(), convergence_report_oneform(), output_meshfunction_paraview(), and output_results().
convergence_comparison_multiple_methods()
template<typename SCALAR , typename MF > void ecu_scheme::post_processing::convergence_comparison_multiple_methods (std::vector< std::pair< ExperimentSolutionWrapper< SCALAR >, std::string >> solution_wrappers_with_name, MF & exact_solution, std::string experiment_name, bool isLinear = false)
Compare the convergence of multiple methods.
Template Parameters
SCALAR type of the solution vector
MF type of exact solution mesh function
Parameters
solution_wrappers_with_name vector of pairs containing the corresponding solution wrapper datastructure together with the name of the method used in the experimnt (used to label columns of the results)
exact_solution exact solution mesh function
experiment_name name to identify the experiment corresponding to the solutions
isLinear flag for determining if we look at a linear FE space or quadratic FE space - default is quadratic
Definition at line 322 of file results_processing.h.
References ComputeMeshWidthTria(), concat(), eoc(), lf::fe::IntegrateMeshFunction(), lf::fe::MeshFunctionFE(), and lf::refinement::MeshHierarchy::PrintInfo().
convergence_comparison_toSUPG()
template<typename SCALAR , typename MF > void ecu_scheme::post_processing::convergence_comparison_toSUPG (const ExperimentSolutionWrapper< SCALAR > & solution_collection_wrapper_one, const ExperimentSolutionWrapper< SCALAR > & solution_collection_wrapper_two, MF & mf_exact_solution, std::string experiment_name, bool isLinear = false)
Definition at line 226 of file results_processing.h.
References ComputeMeshWidthTria(), concat(), eoc(), ecu_scheme::post_processing::ExperimentSolutionWrapper< SCALAR >::eps, ecu_scheme::post_processing::ExperimentSolutionWrapper< SCALAR >::final_time_solutions, lf::fe::IntegrateMeshFunction(), ecu_scheme::post_processing::ExperimentSolutionWrapper< SCALAR >::mesh_hierarchy_p, lf::fe::MeshFunctionFE(), and ecu_scheme::post_processing::ExperimentSolutionWrapper< SCALAR >::refinement_levels.
convergence_report_oneform()
template<typename SCALAR , typename MF > void ecu_scheme::post_processing::convergence_report_oneform (const ExperimentSolutionWrapper< SCALAR > & solution_collection_wrapper, MF & mf_exact_solution, std::string experiment_name, bool isLinear = false)
Definition at line 113 of file results_processing.h.
References ComputeMeshWidthTria(), concat(), eoc(), ecu_scheme::post_processing::ExperimentSolutionWrapper< SCALAR >::eps, ecu_scheme::post_processing::ExperimentSolutionWrapper< SCALAR >::final_time_solutions, lf::base::RefEl::kSegment(), lf::base::RefEl::kTria(), L2norm(), lf::quad::make_QuadRule(), ecu_scheme::post_processing::ExperimentSolutionWrapper< SCALAR >::mesh_hierarchy_p, lf::assemble::DofHandler::NumDofs(), and ecu_scheme::post_processing::ExperimentSolutionWrapper< SCALAR >::refinement_levels.
eoc()
double ecu_scheme::post_processing::eoc (Eigen::VectorXd & N, Eigen::VectorXd & err, unsigned int from_index = 0)
Definition at line 47 of file results_processing.h.
References linearFit().
Referenced by convergence_comparison_multiple_methods(), convergence_comparison_toSUPG(), and convergence_report_oneform().
EvaluateMeshFunction() [1/2]
template<typename MF > double ecu_scheme::post_processing::EvaluateMeshFunction (std::shared_ptr< const lf::mesh::Mesh > mesh_p, MF mf, const Eigen::Vector2d & global, double tol = 10E-10)
Evaluates a MeshFunction at a point specified by its global coordinates.
Template Parameters
MF a mesh function type
Parameters
mesh_p underlying triangular mesh
mf mesh function to evaluate
global point expressed in global coordinates
tol tolerance for the search of the cell containing the point
Returns
value of the mesh function at the point
Definition at line 36 of file ecu_tools.h.
References lf::geometry::Corners(), lf::geometry::Geometry::Geometry(), lf::base::RefEl::kTria(), and lf::base::RefEl::RefEl().
EvaluateMeshFunction() [2/2]
template<typename MF > std::vector<double> ecu_scheme::post_processing::EvaluateMeshFunction (std::shared_ptr< const lf::mesh::Mesh > mesh_p, MF mf, const std::vector< Eigen::Vector2d > & global, double tol = 10E-10)
Evaluates a MeshFunction at a set of points specified by their global coordinates.
Template Parameters
MF mesh function type
Parameters
mesh_p underlying triangular mesh
mf mesh function of type MF
global set of points expressed in global coordinates
tol tolerance for the search of the cell containing the point
Returns
vector containing the values of the mesh function at the points
Definition at line 73 of file ecu_tools.h.
References lf::geometry::Corners(), lf::geometry::Geometry::Geometry(), lf::base::RefEl::kTria(), and lf::base::RefEl::RefEl().
H1seminorm()
template<typename MF , typename SQ_F > std::pair<double, lf::mesh::utils::CodimMeshDataSet<double> > ecu_scheme::post_processing::H1seminorm (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p, const MF & f, const SQ_F & sq_f, const lf::quad::QuadRule & quad_rule)
Definition at line 51 of file norms.h.
References lf::quad::QuadRule::NumPoints(), and lf::quad::QuadRule::Points().
L2norm()
template<class MF , typename SQ_F > std::pair<double, lf::mesh::utils::CodimMeshDataSet<double> > ecu_scheme::post_processing::L2norm (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p, const MF & f, const SQ_F & sq_f, const lf::quad::QuadRule & quad_rule)
Definition at line 19 of file norms.h.
References lf::quad::QuadRule::NumPoints(), lf::quad::QuadRule::Points(), and lf::quad::QuadRule::Weights().
Referenced by convergence_report_oneform().
linearFit()
Eigen::Vector2d ecu_scheme::post_processing::linearFit (const Eigen::VectorXd & x, const Eigen::VectorXd & y)
Definition at line 37 of file results_processing.h.
Referenced by eoc().
output_meshfunction_paraview()
template<typename SCALAR , typename MF > void ecu_scheme::post_processing::output_meshfunction_paraview (std::shared_ptr< const lf::fe::ScalarFESpace< SCALAR >> fe_space, MF & mf_analytic, std::string file_name)
Definition at line 84 of file results_processing.h.
References concat(), and lf::io::VtkWriter::WritePointData().
output_results()
template<typename SCALAR > void ecu_scheme::post_processing::output_results (const std::shared_ptr< lf::fe::ScalarFESpace< SCALAR >> & fe_space, Eigen::VectorXd solution_vec, std::string experiment_name)
Definition at line 98 of file results_processing.h.
References concat(), and lf::io::VtkWriter::WritePointData().
SampleMeshFunctionOnCurve()
template<typename CURVE , typename MF > void ecu_scheme::post_processing::SampleMeshFunctionOnCurve (std::shared_ptr< const lf::mesh::Mesh > mesh_p, const CURVE & gamma, const MF & mf, unsigned int num_points, const std::string & file_name, std::pair< double, double > interval = {0.0, 1.0})
Sample a mesh function at points along a curve.
Template Parameters
CURVE type of the curve function
MF type of the mesh function
Parameters
mesh_p underlying triangular mesh
gamma function representing the curve
mf mesh function to sample
num_points number of points to sample
file_name name of the file to write the results to
Definition at line 127 of file ecu_tools.h.