LehrFEM++: ecu_scheme::assemble Namespace Reference
ecu_scheme::assemble Namespace Reference
Collection of matrix and vector element providers.
Classes
class ConvectionUpwindMatrixProvider
Class for the computation of the element matrix corresponding to the convective term The element matrix provider evaluates the convective bilinear form for the midpoint upwind scheme:
class EdgeElementGradMatrixProvider
Class providing the edge element gradient matrix for a given FE space and velocity field \(\vec{\beta}\). The element matrix provider evaluates part of the bilinear form for 1-forms from section 3.1, namely:
class EdgeElementMassMatrixProvider
Class providing the edge element mass matrix for a given FE space and velocity field \(\vec{\beta}\). The element matrix provider evaluates part of the bilinear form for 1-forms from section 3.1, namely:
class FifteenPointUpwindMatrixProvider
Class providing the element matrix for the 15-point upwind scheme The element matrix provider evaluates the convective bilinear form for the 15-point upwind scheme \(b_h^{full}(u_h,v_h) \) presented in section 2.1.1 of the thesis.
class MeshFunctionOneForm
Class representing the implementation of a Mesh Function for 1-forms.
class StableConvectionUpwindMatrixProvider
Class providing the element matrix for the 7-point upwind scheme The element matrix provider evaluates the convective bilinear form for the 7-point upwind scheme \(b_h^{vmb}(u_h,v_h) \) presented in section 2.1.1 of the thesis.
class SupgConvectiveEMP
Computes the local matrices for the convective term based on linear FE and trapezoidal rule.
class SupgStabilizationEMP
Computes the local matrices for the stabilization term in the SUPG method based on linear finite elements and the trapezoidal rule .
class SUPGElementMatrixProvider
Assemble the SUPG element matrix for the convection-diffusion boundary for quadratic Lagrange FE value problem where the implementation is based on a combination of techniques from the NumPDE lecture document.
Functions
void EnforceBoundaryConditions (const std::shared_ptr< lf::uscalfe::UniformScalarFESpace< double >> &fe_space, lf::assemble::COOMatrix< double > &A, Eigen::VectorXd &phi, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet)
Enforce Dirichlet boundary conditions for the convection-diffusion problem The boundary in question corresponds to the inflow boundary on the unit rectangle where the velocity field is assumed to have the form \(\vec{v} = (c, c)^T\) for some constant \(c\). Thus the inflow boundary is \(\Gamma = \Gamma_1 \cup \Gamma2 \) with \(\Gamma_1 = \{(x, y) \in [0, 1]^2 \mid x = 0 \} \), and \(\Gamma_2 = \{(x, y) \in [0, 1]^2 \mid y = 0 \} \).
void EnforceBoundaryConditionsOnRotInflow (const std::shared_ptr< lf::uscalfe::UniformScalarFESpace< double >> &fe_space, lf::assemble::COOMatrix< double > &A, Eigen::VectorXd &phi, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet)
Enforce Dirichlet boundary conditions for the convection-diffusion problem The boundary corresponds to the inflow boundary on the unit rectangle where we assume a rotational velocity field such that the inflow boundary has the following form: \(\Gamma = \Gamma_1 \cup \Gamma2 \) with \(\Gamma_1 = \{(x, y) \in [0, 1]^2 \mid x = 1 \} \), and \(\Gamma_2 = \{(x, y) \in [0, 1]^2 \mid y = 0 \} \).
lf::mesh::utils::CodimMeshDataSet< double > initializeMasses (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p)
Computes the masses m(p) of all vertices of the mesh in the linear FE space case.
lf::mesh::utils::CodimMeshDataSet< double > initializeMassesQuadratic (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p)
Computes the masses m(p) of all vertices of the mesh in the quadratic FE space case.
lf::mesh::utils::CodimMeshDataSet< double > initializeMassesQuadraticEdges (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p)
Computes the masses m(p) of all midpoints of edges of the mesh in the quadratic FE space case.
Eigen::Matrix< double, 2, 3 > computeOutwardNormalsTria (const lf::mesh::Entity &entity)
Computes the outward normals of a triangular cell.
std::vector< std::tuple< Eigen::Vector2d, double, bool > > prepareFifteenPointQuadRule ()
Prepare the 15-point quadrature rule for the reference triangle Location of points is generated such that: they have the form \((\frac{i}{p}, \frac{j}{p})\) for i, j integeres in {0,1,...,p} and \(i+j \leq p\) Weights are computed such that the quadrature rule is exact for polynomials of degree 4.
lf::mesh::utils::CodimMeshDataSet< double > initMassesVerticesFifteenQuadRule (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p)
Computes the masses m(p) of all vertices of triangles in the mesh.
lf::mesh::utils::CodimMeshDataSet< double > initMassesEdgeMidpointsFifteenQuadRule (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p)
Computes the masses m(p) of all midpoints of edges of triangles in the mesh.
lf::mesh::utils::CodimMeshDataSet< double > initMassesEdgeOffFifteenQuadRule (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p)
Computes the masses m(p) of all quadrature points lying on edges (that are not midpoints of the edge) of triangles in the mesh.
lf::mesh::utils::CodimMeshDataSet< double > initMassesCellsFifteenQuadRule (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p)
Computes the masses m(p) of all quadrature points lying inside triangle cells of the mesh.
lf::mesh::utils::CodimMeshDataSet< double > initMassesVert (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p)
Computes the masses m(p) for the \(b_h^{vmb}\) scheme of all vertices of the mesh.
lf::mesh::utils::CodimMeshDataSet< double > initMassesEdges (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p)
Computes the masses m(p) for the \(b_h^{vmb}\) scheme of all midpoints of edges of the mesh.
lf::mesh::utils::CodimMeshDataSet< double > initMassesCells (const std::shared_ptr< const lf::mesh::Mesh > &mesh_p)
Computes the masses m(p) for the \(b_h^{vmb}\) scheme of all cells of the mesh.
double Diameter (const lf::mesh::Entity &entity)
Computes the diameter of a TRIANGULAR mesh entity.
double Delta (const lf::mesh::Entity &entity, double eps, Eigen::Vector2d v)
Computes the local control parameter delta for the SUPG method.
template<typename DIFFUSION_COEFF , typename CONVECTION_COEFF , typename FUNCTOR_F , typename FUNCTOR_G >
Eigen::VectorXd SolveCDBVPSupg (const std::shared_ptr< lf::uscalfe::FeSpaceLagrangeO1< double >> &fe_space, DIFFUSION_COEFF eps, CONVECTION_COEFF v, FUNCTOR_F f, FUNCTOR_G g)
Solves the Convection-Diffusion BVP with nonhomogeneous Dirichlet boundary conditions using the SUPG method in the linear FE case.
template<typename DIFFUSION_COEFF , typename CONVECTION_COEFF , typename FUNCTOR_F , typename FUNCTOR_G >
Eigen::VectorXd SolveCDBVPSupgQuad (const std::shared_ptr< lf::uscalfe::FeSpaceLagrangeO2< double >> &fe_space, DIFFUSION_COEFF eps, CONVECTION_COEFF v, FUNCTOR_F f, FUNCTOR_G g, bool flagInflow=false)
Solve the convection-diffusion boundary value problem using the SUPG method for quadratic Lagrangian FE space.
Detailed Description
Collection of matrix and vector element providers.
Function Documentation
computeOutwardNormalsTria()
Eigen::Matrix< double, 2, 3 > ecu_scheme::assemble::computeOutwardNormalsTria (const lf::mesh::Entity & entity)
Computes the outward normals of a triangular cell.
Parameters
entity the triangular cell
Returns
Matrix containing the outward normals of the triangular cell
Parameters
entity Cell for which the outward normals should be computed
Returns
Matrix containing the outward normals of the cell
Definition at line 75 of file convection_upwind_matrix_provider.cc.
References lf::geometry::Corners(), and lf::mesh::Entity::Geometry().
Referenced by ecu_scheme::assemble::ConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::Eval(), ecu_scheme::assemble::FifteenPointUpwindMatrixProvider< SCALAR, FUNCTOR >::Eval(), ecu_scheme::assemble::StableConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::Eval(), and ecu_scheme::assemble::EdgeElementMassMatrixProvider< SCALAR, FUNCTOR >::Eval().
Delta()
double ecu_scheme::assemble::Delta (const lf::mesh::Entity & entity, double eps, Eigen::Vector2d v)
Computes the local control parameter delta for the SUPG method.
Definition at line 32 of file supg_linear_matrix_provider.cc.
References Diameter().
Referenced by ecu_scheme::assemble::SupgStabilizationEMP< FUNCTOR_EPS, FUNCTOR_V, FUNCTOR_F >::Eval().
Diameter()
double ecu_scheme::assemble::Diameter (const lf::mesh::Entity & entity)
Computes the diameter of a TRIANGULAR mesh entity.
Definition at line 6 of file supg_linear_matrix_provider.cc.
References lf::geometry::Corners(), lf::mesh::Entity::Geometry(), lf::base::RefEl::kQuad(), lf::base::RefEl::kTria(), lf::mesh::Entity::RefEl(), and lf::base::RefEl::ToString().
Referenced by Delta().
EnforceBoundaryConditions()
void ecu_scheme::assemble::EnforceBoundaryConditions (const std::shared_ptr< lf::uscalfe::UniformScalarFESpace< double >> & fe_space, lf::assemble::COOMatrix< double > & A, Eigen::VectorXd & phi, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet)
Enforce Dirichlet boundary conditions for the convection-diffusion problem The boundary in question corresponds to the inflow boundary on the unit rectangle where the velocity field is assumed to have the form \(\vec{v} = (c, c)^T\) for some constant \(c\). Thus the inflow boundary is \(\Gamma = \Gamma_1 \cup \Gamma2 \) with \(\Gamma_1 = \{(x, y) \in [0, 1]^2 \mid x = 0 \} \), and \(\Gamma_2 = \{(x, y) \in [0, 1]^2 \mid y = 0 \} \).
Parameters
fe_space underlying FE space
A Galerkin matrix
phi Right-hand side vector
dirichlet Dirichlet boundary condition function
Definition at line 6 of file bdc_utils.cc.
References lf::geometry::Corners(), lf::geometry::Geometry::Geometry(), lf::fe::InitEssentialConditionFromFunction(), lf::base::RefEl::kPoint(), and lf::base::RefEl::kSegment().
Referenced by ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeFifteenPointQuadRuleSolution(), ecu_scheme::experiments::ConstVeloSolution< SCALAR >::ComputeSolution(), ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeStableSolution(), ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeSUPGSolution(), and SolveCDBVPSupgQuad().
EnforceBoundaryConditionsOnRotInflow()
void ecu_scheme::assemble::EnforceBoundaryConditionsOnRotInflow (const std::shared_ptr< lf::uscalfe::UniformScalarFESpace< double >> & fe_space, lf::assemble::COOMatrix< double > & A, Eigen::VectorXd & phi, std::function< double(const Eigen::Matrix< double, 2, 1, 0 > &)> dirichlet)
Enforce Dirichlet boundary conditions for the convection-diffusion problem The boundary corresponds to the inflow boundary on the unit rectangle where we assume a rotational velocity field such that the inflow boundary has the following form: \(\Gamma = \Gamma_1 \cup \Gamma2 \) with \(\Gamma_1 = \{(x, y) \in [0, 1]^2 \mid x = 1 \} \), and \(\Gamma_2 = \{(x, y) \in [0, 1]^2 \mid y = 0 \} \).
Parameters
fe_space underlying FE space
A Galerkin matrix
phi Right-hand side vector
dirichlet Dirichlet boundary condition function
Definition at line 51 of file bdc_utils.cc.
References lf::geometry::Corners(), lf::geometry::Geometry::Geometry(), lf::fe::InitEssentialConditionFromFunction(), lf::base::RefEl::kPoint(), and lf::base::RefEl::kSegment().
Referenced by ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolutionMultipleMethods(), and SolveCDBVPSupgQuad().
initializeMasses()
lf::mesh::utils::CodimMeshDataSet< double > ecu_scheme::assemble::initializeMasses (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p)
Computes the masses m(p) of all vertices of the mesh in the linear FE space case.
Computes the masses m(p) of all vertices of the mesh for the linear finite element space.
Parameters
mesh_p pointer to the mesh
Returns
Data structure containing the masses m(p) for all vertices of the mesh represented by mesh_p.
Parameters
mesh_p pointer to the mesh
Returns
data structure containing the masses m(p) for all vertices of the mesh represented by mesh_p
Definition at line 17 of file convection_upwind_matrix_provider.cc.
References lf::geometry::Geometry::Geometry(), lf::mesh::Entity::SubEntities(), and lf::geometry::Volume().
Referenced by ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolution(), ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeSolution(), and ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolutionMultipleMethods().
initializeMassesQuadratic()
lf::mesh::utils::CodimMeshDataSet< double > ecu_scheme::assemble::initializeMassesQuadratic (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p)
Computes the masses m(p) of all vertices of the mesh in the quadratic FE space case.
Computes the masses m(p) of all vertices of the mesh for the quadratic finite element space.
Parameters
mesh_p pointer to the mesh
Returns
Data structure containing the masses m(p) for all vertices of the mesh represented by mesh_p.
Parameters
mesh_p pointer to the mesh
Returns
data structure containing the masses m(p) for all vertices of the mesh represented by mesh_p
Definition at line 37 of file convection_upwind_matrix_provider.cc.
References lf::geometry::Geometry::Geometry(), lf::mesh::Entity::SubEntities(), and lf::geometry::Volume().
Referenced by ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolution(), ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeSolution(), ecu_scheme::experiments::ConstVeloSolution< SCALAR >::ComputeSolution(), and ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolutionMultipleMethods().
initializeMassesQuadraticEdges()
lf::mesh::utils::CodimMeshDataSet< double > ecu_scheme::assemble::initializeMassesQuadraticEdges (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p)
Computes the masses m(p) of all midpoints of edges of the mesh in the quadratic FE space case.
Computes the masses m(p) of all edge midpoints of the mesh for the quadratic finite element space.
Parameters
mesh_p pointer to the mesh
Returns
Data structure containing the masses m(p) for all midpoints of edges of the mesh represented by mesh_p.
Parameters
mesh_p pointer to the mesh
Returns
data structure containing the masses m(p) for all edge midpoints of the mesh represented by mesh_p
Definition at line 57 of file convection_upwind_matrix_provider.cc.
References lf::geometry::Geometry::Geometry(), lf::mesh::Entity::SubEntities(), and lf::geometry::Volume().
Referenced by ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolution(), ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeSolution(), ecu_scheme::experiments::ConstVeloSolution< SCALAR >::ComputeSolution(), and ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolutionMultipleMethods().
initMassesCells()
lf::mesh::utils::CodimMeshDataSet< double > ecu_scheme::assemble::initMassesCells (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p)
Computes the masses m(p) for the \(b_h^{vmb}\) scheme of all cells of the mesh.
Parameters
mesh_p underlying mesh
Returns
Data structure containing the masses m(p) for all cells of the mesh
Definition at line 31 of file stable_convection_prov.cc.
References lf::geometry::Geometry::Geometry(), and lf::geometry::Volume().
Referenced by ecu_scheme::experiments::ConstVeloSolution< SCALAR >::ComputeSolution(), ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolutionMultipleMethods(), and ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeStableSolution().
initMassesCellsFifteenQuadRule()
lf::mesh::utils::CodimMeshDataSet< double > ecu_scheme::assemble::initMassesCellsFifteenQuadRule (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p)
Computes the masses m(p) of all quadrature points lying inside triangle cells of the mesh.
Parameters
mesh_p underlying mesh
Returns
Data structure containing the masses m(p) for all quadrature points lying inside triangle cells of the mesh
Definition at line 89 of file fifteen_point_upwind_matrix_provider.cc.
References lf::geometry::Geometry::Geometry(), and lf::geometry::Volume().
Referenced by ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeFifteenPointQuadRuleSolution(), and ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolutionMultipleMethods().
initMassesEdgeMidpointsFifteenQuadRule()
lf::mesh::utils::CodimMeshDataSet< double > ecu_scheme::assemble::initMassesEdgeMidpointsFifteenQuadRule (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p)
Computes the masses m(p) of all midpoints of edges of triangles in the mesh.
Parameters
mesh_p underlying mesh
Returns
Data structure containing the masses m(p) for all midpoints of edges of the mesh
Definition at line 61 of file fifteen_point_upwind_matrix_provider.cc.
References lf::geometry::Geometry::Geometry(), lf::mesh::Entity::SubEntities(), and lf::geometry::Volume().
Referenced by ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeFifteenPointQuadRuleSolution(), and ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolutionMultipleMethods().
initMassesEdgeOffFifteenQuadRule()
lf::mesh::utils::CodimMeshDataSet< double > ecu_scheme::assemble::initMassesEdgeOffFifteenQuadRule (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p)
Computes the masses m(p) of all quadrature points lying on edges (that are not midpoints of the edge) of triangles in the mesh.
Parameters
mesh_p underlying mesh
Returns
Data structure containing the masses m(p) for all quadrature points lying on edges of the mesh
Definition at line 75 of file fifteen_point_upwind_matrix_provider.cc.
References lf::geometry::Geometry::Geometry(), lf::mesh::Entity::SubEntities(), and lf::geometry::Volume().
Referenced by ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeFifteenPointQuadRuleSolution(), and ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolutionMultipleMethods().
initMassesEdges()
lf::mesh::utils::CodimMeshDataSet< double > ecu_scheme::assemble::initMassesEdges (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p)
Computes the masses m(p) for the \(b_h^{vmb}\) scheme of all midpoints of edges of the mesh.
Parameters
mesh_p underlying mesh
Returns
Data structure containing the masses m(p) for all midpoints of edges of the mesh
Definition at line 18 of file stable_convection_prov.cc.
References lf::geometry::Geometry::Geometry(), lf::mesh::Entity::SubEntities(), and lf::geometry::Volume().
Referenced by ecu_scheme::experiments::ConstVeloSolution< SCALAR >::ComputeSolution(), ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolutionMultipleMethods(), and ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeStableSolution().
initMassesVert()
lf::mesh::utils::CodimMeshDataSet< double > ecu_scheme::assemble::initMassesVert (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p)
Computes the masses m(p) for the \(b_h^{vmb}\) scheme of all vertices of the mesh.
Parameters
mesh_p underlying mesh
Returns
Data structure containing the masses m(p) for all vertices of the mesh
Definition at line 5 of file stable_convection_prov.cc.
References lf::geometry::Geometry::Geometry(), lf::mesh::Entity::SubEntities(), and lf::geometry::Volume().
Referenced by ecu_scheme::experiments::ConstVeloSolution< SCALAR >::ComputeSolution(), ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolutionMultipleMethods(), and ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeStableSolution().
initMassesVerticesFifteenQuadRule()
lf::mesh::utils::CodimMeshDataSet< double > ecu_scheme::assemble::initMassesVerticesFifteenQuadRule (const std::shared_ptr< const lf::mesh::Mesh > & mesh_p)
Computes the masses m(p) of all vertices of triangles in the mesh.
Parameters
mesh_p underlying mesh
Returns
Data structure containing the masses m(p) for all vertices of the mesh
Definition at line 46 of file fifteen_point_upwind_matrix_provider.cc.
References lf::geometry::Geometry::Geometry(), lf::mesh::Entity::SubEntities(), and lf::geometry::Volume().
Referenced by ecu_scheme::experiments::ManufacturedSolutionExperiment< SCALAR >::ComputeFifteenPointQuadRuleSolution(), and ecu_scheme::experiments::ConcentricStreamSolution< SCALAR >::ComputeSolutionMultipleMethods().
prepareFifteenPointQuadRule()
std::vector< std::tuple< Eigen::Vector2d, double, bool > > ecu_scheme::assemble::prepareFifteenPointQuadRule ()
Prepare the 15-point quadrature rule for the reference triangle Location of points is generated such that: they have the form \((\frac{i}{p}, \frac{j}{p})\) for i, j integeres in {0,1,...,p} and \(i+j \leq p\) Weights are computed such that the quadrature rule is exact for polynomials of degree 4.
Returns
a vector of pairs, where each pair contains a quadrature point and its weight
Definition at line 8 of file fifteen_point_upwind_matrix_provider.cc.
Referenced by ecu_scheme::assemble::FifteenPointUpwindMatrixProvider< SCALAR, FUNCTOR >::Eval().
SolveCDBVPSupg()
template<typename DIFFUSION_COEFF , typename CONVECTION_COEFF , typename FUNCTOR_F , typename FUNCTOR_G > Eigen::VectorXd ecu_scheme::assemble::SolveCDBVPSupg (const std::shared_ptr< lf::uscalfe::FeSpaceLagrangeO1< double >> & fe_space, DIFFUSION_COEFF eps, CONVECTION_COEFF v, FUNCTOR_F f, FUNCTOR_G g)
Solves the Convection-Diffusion BVP with nonhomogeneous Dirichlet boundary conditions using the SUPG method in the linear FE case.
Template Parameters
DIFFUSION_COEFF diffusion coefficient
CONVECTION_COEFF convection coefficient
FUNCTOR_F source function
FUNCTOR_G Dirichlet boundary function
Parameters
fe_space underlying FE space
eps parameter for the diffusive term
v velocity field
f source function
g Dirichlet boundary function
Returns
Solution vector
Definition at line 169 of file supg_linear_matrix_provider.h.
References lf::assemble::AssembleMatrixLocally(), lf::assemble::AssembleVectorLocally(), lf::mesh::utils::flagEntitiesOnBoundary(), lf::fe::InitEssentialConditionFromFunction(), lf::base::RefEl::kSegment(), and lf::assemble::COOMatrix< SCALAR >::makeSparse().
SolveCDBVPSupgQuad()
template<typename DIFFUSION_COEFF , typename CONVECTION_COEFF , typename FUNCTOR_F , typename FUNCTOR_G > Eigen::VectorXd ecu_scheme::assemble::SolveCDBVPSupgQuad (const std::shared_ptr< lf::uscalfe::FeSpaceLagrangeO2< double >> & fe_space, DIFFUSION_COEFF eps, CONVECTION_COEFF v, FUNCTOR_F f, FUNCTOR_G g, bool flagInflow = false)
Solve the convection-diffusion boundary value problem using the SUPG method for quadratic Lagrangian FE space.
Template Parameters
DIFFUSION_COEFF diffusion coefficient type
CONVECTION_COEFF convection coefficient type
FUNCTOR_F the source function type
FUNCTOR_G Dirichlet boundary function type
Parameters
fe_space underlying FE space
eps epsilon parameter for the diffusive term
v velocity field
f source function
g Dirichlet boundary function
flagInflow flag to indicate what kind of inflow boundary we have, if true we have rotational inflow, otherwise we have the standard inflow
Returns
solution vector
Definition at line 160 of file supg_matrix_provider.h.
References lf::assemble::AssembleMatrixLocally(), lf::assemble::AssembleVectorLocally(), EnforceBoundaryConditions(), EnforceBoundaryConditionsOnRotInflow(), and lf::assemble::COOMatrix< SCALAR >::makeSparse().