LehrFEM++: ecu_scheme::assemble::StableConvectionUpwindMatrixProvider< SCALAR, FUNCTOR > Class Template Reference
ecu_scheme::assemble::StableConvectionUpwindMatrixProvider< SCALAR, FUNCTOR > Class Template Reference
Class providing the element matrix for the 7-point upwind scheme The element matrix provider evaluates the convective bilinear form for the 7-point upwind scheme \(b_h^{vmb}(u_h,v_h) \) presented in section 2.1.1 of the thesis.
#include </home/gori/Documents/Thesis/thesis-lehrfempp-repo/lehrfempp/projects/ecu_scheme/assemble/stable_convection_prov.h>
Public Member Functions
StableConvectionUpwindMatrixProvider (const std::shared_ptr< lf::fe::ScalarFESpace< SCALAR >> &fe_space, FUNCTOR v, lf::mesh::utils::CodimMeshDataSet< double > masses_vertices, lf::mesh::utils::CodimMeshDataSet< double > masses_edges, lf::mesh::utils::CodimMeshDataSet< double > masses_cells)
Constructor for the 7-point scheme element matrix provider.
Eigen::Matrix< SCALAR, 6, 6 > Eval (const lf::mesh::Entity &entity)
Evaluates the element matrix for a given entity.
bool isActive (const lf::mesh::Entity &) const
Default implementation: all cells are active.
Private Attributes
FUNCTOR v_
std::shared_ptr< lf::fe::ScalarFESpace< SCALAR > > fe_space_
lf::mesh::utils::CodimMeshDataSet< double > masses_vertices_
lf::mesh::utils::CodimMeshDataSet< double > masses_edges_
lf::mesh::utils::CodimMeshDataSet< double > masses_cells_
Detailed Description
template<typename SCALAR, typename FUNCTOR>
class ecu_scheme::assemble::StableConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >
Class providing the element matrix for the 7-point upwind scheme The element matrix provider evaluates the convective bilinear form for the 7-point upwind scheme \(b_h^{vmb}(u_h,v_h) \) presented in section 2.1.1 of the thesis.
Template Parameters
SCALAR the scalar type of the FE space
FUNCTOR the type of the velocity field \(\vec{\beta}\)
Definition at line 52 of file stable_convection_prov.h.
Constructor & Destructor Documentation
StableConvectionUpwindMatrixProvider()
template<typename SCALAR , typename FUNCTOR > ecu_scheme::assemble::StableConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::StableConvectionUpwindMatrixProvider (const std::shared_ptr< lf::fe::ScalarFESpace< SCALAR >> & fe_space, FUNCTOR v, lf::mesh::utils::CodimMeshDataSet< double > masses_vertices, lf::mesh::utils::CodimMeshDataSet< double > masses_edges, lf::mesh::utils::CodimMeshDataSet< double > masses_cells)
Constructor for the 7-point scheme element matrix provider.
Parameters
fe_space underlying FE space
v velocity field \(\vec{\beta}\)
masses_vertices Data structure containing the masses m(p) for all vertices of the mesh
masses_edges Data structure containing the masses m(p) for all midpoints of edges of the mesh
masses_cells Data structure containing the masses m(p) for all cells of the mesh
Definition at line 90 of file stable_convection_prov.h.
Member Function Documentation
Eval()
template<typename SCALAR , typename FUNCTOR > Eigen::Matrix< SCALAR, 6, 6 > ecu_scheme::assemble::StableConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::Eval (const lf::mesh::Entity & entity)
Evaluates the element matrix for a given entity.
Parameters
entity underlying entity
Returns
Element matrix
Definition at line 104 of file stable_convection_prov.h.
References ecu_scheme::assemble::computeOutwardNormalsTria(), lf::geometry::Corners(), lf::mesh::Entity::Geometry(), lf::mesh::Entity::SubEntities(), and lf::geometry::Volume().
isActive()
template<typename SCALAR , typename FUNCTOR > bool ecu_scheme::assemble::StableConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::isActive (const lf::mesh::Entity &) const inline
Default implementation: all cells are active.
Definition at line 79 of file stable_convection_prov.h.
Member Data Documentation
fe_space_
template<typename SCALAR , typename FUNCTOR > std::shared_ptr<lf::fe::ScalarFESpace<SCALAR> > ecu_scheme::assemble::StableConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::fe_space_ private
Definition at line 83 of file stable_convection_prov.h.
masses_cells_
template<typename SCALAR , typename FUNCTOR > lf::mesh::utils::CodimMeshDataSet<double> ecu_scheme::assemble::StableConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::masses_cells_ private
Definition at line 86 of file stable_convection_prov.h.
masses_edges_
template<typename SCALAR , typename FUNCTOR > lf::mesh::utils::CodimMeshDataSet<double> ecu_scheme::assemble::StableConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::masses_edges_ private
Definition at line 85 of file stable_convection_prov.h.
masses_vertices_
template<typename SCALAR , typename FUNCTOR > lf::mesh::utils::CodimMeshDataSet<double> ecu_scheme::assemble::StableConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::masses_vertices_ private
Definition at line 84 of file stable_convection_prov.h.
v_
template<typename SCALAR , typename FUNCTOR > FUNCTOR ecu_scheme::assemble::StableConvectionUpwindMatrixProvider< SCALAR, FUNCTOR >::v_ private
Definition at line 82 of file stable_convection_prov.h.
The documentation for this class was generated from the following file:
/home/gori/Documents/Thesis/thesis-lehrfempp-repo/lehrfempp/projects/ecu_scheme/assemble/stable_convection_prov.h