LehrFEM++: ecu_scheme::assemble::EdgeElementMassMatrixProvider< SCALAR, FUNCTOR > Class Template Reference
ecu_scheme::assemble::EdgeElementMassMatrixProvider< SCALAR, FUNCTOR > Class Template Reference
Class providing the edge element mass matrix for a given FE space and velocity field \(\vec{\beta}\). The element matrix provider evaluates part of the bilinear form for 1-forms from section 3.1, namely:
#include </home/gori/Documents/Thesis/thesis-lehrfempp-repo/lehrfempp/projects/ecu_scheme/assemble/edge_element_mass_matrix_provider.h>
Public Member Functions
EdgeElementMassMatrixProvider (const std::shared_ptr< lf::fe::ScalarFESpace< SCALAR >> &fe_space, FUNCTOR v)
Constructor for the edge element mass matrix provider.
Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > Eval (const lf::mesh::Entity &entity) const
Evaluates the edge element mass matrix for a given entity.
bool isActive (const lf::mesh::Entity &) const
Default implementation: all cells are active.
Private Attributes
FUNCTOR v_
std::shared_ptr< lf::fe::ScalarFESpace< SCALAR > > fe_space_
Detailed Description
template<typename SCALAR, typename FUNCTOR>
class ecu_scheme::assemble::EdgeElementMassMatrixProvider< SCALAR, FUNCTOR >
Class providing the edge element mass matrix for a given FE space and velocity field \(\vec{\beta}\). The element matrix provider evaluates part of the bilinear form for 1-forms from section 3.1, namely:
\[ (\omega_h, \eta_h) \mapsto \int_T \mathcal{I}_{\vec{\beta}, 1}^1(\mathrm{i}_{\vec{\beta}} \mathrm{d}^1 \omega_h) \wedge \star \eta_h \]
where the basis functions for \(\omega_h, \ \eta_h \) are the edge element basis functions defined as:
\[ \mathbf{\psi}_i = s_i (\lambda_i \mathbf{grad}_{\Gamma}(\lambda_{i+1}) - \lambda_{i+1} \mathbf{grad}_{\Gamma}(\lambda_{i})) \]
Template Parameters
SCALAR the scalar type of the FE space
FUNCTOR the type of the velocity field \(\vec{\beta}\)
Definition at line 32 of file edge_element_mass_matrix_provider.h.
Constructor & Destructor Documentation
EdgeElementMassMatrixProvider()
template<typename SCALAR , typename FUNCTOR > ecu_scheme::assemble::EdgeElementMassMatrixProvider< SCALAR, FUNCTOR >::EdgeElementMassMatrixProvider (const std::shared_ptr< lf::fe::ScalarFESpace< SCALAR >> & fe_space, FUNCTOR v)
Constructor for the edge element mass matrix provider.
Parameters
fe_space the FE space
v the velocity field \(\vec{\beta}\)
Definition at line 59 of file edge_element_mass_matrix_provider.h.
Member Function Documentation
Eval()
template<typename SCALAR , typename FUNCTOR > Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > ecu_scheme::assemble::EdgeElementMassMatrixProvider< SCALAR, FUNCTOR >::Eval (const lf::mesh::Entity & entity) const
Evaluates the edge element mass matrix for a given entity.
Parameters
entity reference to the entity
Returns
Edge element mass matrix
Definition at line 65 of file edge_element_mass_matrix_provider.h.
References ecu_scheme::assemble::computeOutwardNormalsTria(), lf::geometry::Corners(), lf::mesh::Entity::Geometry(), lf::uscalfe::FeLagrangeO1Tria< SCALAR >::GradientsReferenceShapeFunctions(), lf::geometry::Geometry::JacobianInverseGramian(), lf::base::RefEl::kTria(), lf::mesh::Entity::RefEl(), lf::mesh::Entity::RelativeOrientations(), lf::mesh::Entity::SubEntities(), lf::mesh::to_sign(), and lf::geometry::Volume().
isActive()
template<typename SCALAR , typename FUNCTOR > bool ecu_scheme::assemble::EdgeElementMassMatrixProvider< SCALAR, FUNCTOR >::isActive (const lf::mesh::Entity &) const inline
Default implementation: all cells are active.
Definition at line 51 of file edge_element_mass_matrix_provider.h.
Member Data Documentation
fe_space_
template<typename SCALAR , typename FUNCTOR > std::shared_ptr<lf::fe::ScalarFESpace<SCALAR> > ecu_scheme::assemble::EdgeElementMassMatrixProvider< SCALAR, FUNCTOR >::fe_space_ private
Definition at line 55 of file edge_element_mass_matrix_provider.h.
v_
template<typename SCALAR , typename FUNCTOR > FUNCTOR ecu_scheme::assemble::EdgeElementMassMatrixProvider< SCALAR, FUNCTOR >::v_ private
Definition at line 54 of file edge_element_mass_matrix_provider.h.
The documentation for this class was generated from the following file:
/home/gori/Documents/Thesis/thesis-lehrfempp-repo/lehrfempp/projects/ecu_scheme/assemble/edge_element_mass_matrix_provider.h